// flow-typed signature: 7ec74ef1ca5380d1f82dae91368ccf91
// flow-typed version: <<STUB>>/metro-core_v0.28.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'metro-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'metro-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'metro-core/src/formatBanner/formatBanner' {
  declare module.exports: any;
}

declare module 'metro-core/src/formatBanner/index' {
  declare module.exports: any;
}

declare module 'metro-core/src/index' {
  declare module.exports: any;
}

declare module 'metro-core/src/Logger/index' {
  declare module.exports: any;
}

declare module 'metro-core/src/Logger/Logger' {
  declare module.exports: any;
}

declare module 'metro-core/src/Terminal/index' {
  declare module.exports: any;
}

declare module 'metro-core/src/Terminal/Terminal' {
  declare module.exports: any;
}

// Filename aliases
declare module 'metro-core/src/formatBanner/formatBanner.js' {
  declare module.exports: $Exports<'metro-core/src/formatBanner/formatBanner'>;
}
declare module 'metro-core/src/formatBanner/index.js' {
  declare module.exports: $Exports<'metro-core/src/formatBanner/index'>;
}
declare module 'metro-core/src/index.js' {
  declare module.exports: $Exports<'metro-core/src/index'>;
}
declare module 'metro-core/src/Logger/index.js' {
  declare module.exports: $Exports<'metro-core/src/Logger/index'>;
}
declare module 'metro-core/src/Logger/Logger.js' {
  declare module.exports: $Exports<'metro-core/src/Logger/Logger'>;
}
declare module 'metro-core/src/Terminal/index.js' {
  declare module.exports: $Exports<'metro-core/src/Terminal/index'>;
}
declare module 'metro-core/src/Terminal/Terminal.js' {
  declare module.exports: $Exports<'metro-core/src/Terminal/Terminal'>;
}
